### PR TITLE
implement the dynamic swr withdrawal strategy

### PR DESCRIPTION
**Pull request by jamejone**

### CODE REVIEW

**Comment by jamesplease** [comment]
Thanks for the PR, @jamejone !

I just did a quick pass at the code, and it looks really good! It may be a little bit of time before I have a chance to merge and release this, as I would like to do more research on my end to understand this withdrawal strategy more fully.

I appreciate you putting this together so quickly and opening up such a solid PR ✌️

**Comment by jamejone** [comment]
This will definitely help me too, so it's no problem at all. The formula for DSWR is a basic growing annuity formula:

https://financeformulas.net/Growing-Annuity-Payment.html

I've simply repurposed it. In a way, you're just 'selling' yourself and inflation-adjusted annuity funded by your retirement savings. To be honest, it's really not a radical concept. I imagine I can't be the first to think of it. But I know for sure that almost nobody is aware they can do this, which is what inspired me to define it. Doing a historical backtest will go a long way toward validating it as a viable strategy. Thanks again.

**Comment by jamesplease** [comment]
btw I'm going to make some changes to the folder organization of the repo that will make this PR unable to be merged into master. I just wanted to let you know that you don't need to bother rebasing this; I'll be able to handle the rest from here. Thanks again @jamejone !

**Comment by jamesplease** [comment]
Also, cross-referencing #68

**Comment by jamesplease** [comment]
Just hoppin' in here to let you know that I haven't forgotten about this PR! This past week I've been working on refactoring and adding tests before releasing anything new. Almost done with that work, though, so I should have time to take a look at this within the next week or so ✌️

**Comment by jamejone** [comment]
No worries. Just lmk if you want any help.

**Comment by jamesplease** [comment]
Rebased over in #197 . Closing this PR; follow along there for updates!

**Pull request closed without merging**
